### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by Radcliffe**
I hope that this meets the requirements.

### CODE REVIEW

**Comment by Radcliffe** [comment]
You could also do this with SQL queries.

**Comment by bbertucc** [comment]
Reviewing..

**Review by bbertucc — APPROVED** [review]
Great work!

**Comment by bbertucc** [comment]
@Radcliffe - You have solved the puzzle! #51 bounty is yours! Where would you like the $111 to go? I can either Venmo, Paypal, or donate it in your name to a charity. Feel free to email blake@edupack.dev if you want it to be anonymous.

**Pull request merged**
