### PR TITLE
db: use prepared statements

### LINKED ISSUE #25: Use Prepared statements instead of concatenating user-supplied values
According to [w3](https://www.w3schools.com/php/php_mysql_prepared_statements.asp)..

- Prepared statements reduce parsing time as the preparation on the query is done only once (although the statement is executed multiple times)
- Bound parameters minimize bandwidth to the server as you need send only the parameters each time, and not the whole query
- Prepared statements are very useful against SQL injections, because parameter values, which are transmitted later using a different protocol, need not be correctly escaped. If the original statement template is not derived from external input, SQL injection cannot occur.

Thanks @jrchamp!

### PR DESCRIPTION
**Pull request by jrchamp**
Hi @bbertucc,

I accidentally based this off of the mvp-2 branch. If that's not the right thing to do, I can probably remove some of the extra code and reapply it to main.

If this qualifies for the bounty, please send it to [Instant Messaging Freedom](https://imfreedom.org/donate/), the 501(c)(3) non-profit that helps support open communication tools.

Resolves #25

### CODE REVIEW

**Comment by bbertucc** [comment]
Amazing! Way to go @jrchamp! Pulling off `mvp-2` is totally cool! I'll check it out this week, then transfer $$$. You rock!

**Comment by bbertucc** [comment]
@jrchamp - my apologies for merging and closing this request. I got too excited. Added a few notes for review. Otherwise, everything looks good! Feel free to open another PR.

**Comment by jrchamp** [comment]
I don't see the review notes. Maybe they're stuck in "pending"?

**Comment by bbertucc** [comment]
O yah, I invited you to the repo. 

The notes are just:

- line 31:  this is throwing an error... looks like `bind() `is running on MySQL and not the $statement variable.
- line 434: probably need a single `.` here?

**Comment by jrchamp** [comment]
Sorry, I missed those two. I'll re-open a fresh PR this evening.

**Pull request merged**
